name: CompatHelper
on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Pkg.add CompatHelper
        run: julia -e 'using Pkg; Pkg.add("CompatHelper"); using CompatHelper; CompatHelper.main()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}